### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by dogancelik** [andreafabrizi/rtmpSnoop#24]
Versions: Windows 10, Python 2.7.13

## Instructions

```
pip install git+https://github.com/secdev/scapy
pip install argparse

git clone https://github.com/andreafabrizi/rtmpSnoop.git
cd rtmpSnoop

python rtmpSnoop.py -f dump.pcap
```

## Error

```
rtmpSnoop v0.2.1 - The RTMP Sniffer!
Andrea Fabrizi - andrea.fabrizi@gmail.com

Reading packets from dump file 'dump.pcap'...
Traceback (most recent call last):
  File "rtmpSnoop.py", line 147, in <module>
    sniff(offline=args.pcapfile, filter="tcp", prn = PacketHandler)
  File "D:\Tools\winpython2\python-2.7.13.amd64\lib\site-packages\scapy\sendrecv.py", line 692, in sniff
    )] = offline
  File "D:\Tools\winpython2\python-2.7.13.amd64\lib\site-packages\scapy\utils.py", line 1283, in tcpdump
    stderr=open(os.devnull) if quiet else None,
  File "D:\Tools\winpython2\python-2.7.13.amd64\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "D:\Tools\winpython2\python-2.7.13.amd64\lib\subprocess.py", line 595, in _execute_child
    args = list2cmdline(args)
  File "D:\Tools\winpython2\python-2.7.13.amd64\lib\subprocess.py", line 262, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'NoneType' is not iterable
```

## Related

* [How to get Device Name for `-i`](https://blogs.technet.microsoft.com/heyscriptingguy/2014/01/15/using-powershell-to-find-connected-network-adapters/) (edit: my stream was not a RTMP stream)
* Related issues: secdev/scapy#1 (fixed using git source), secdev/scapy#652 (worth looking into)

Also please change the Windows instructions URL to this one because it doesn't direct to the correct page:

```
https://scapy.readthedocs.io/en/latest/installation.html#windows
```

**Comment by IronCurtainDev** [comment]
even I had this issue. by install following software all of them get solved.
1. python 2.7.2 from python.org
2. Microsoft Visual C++ Compiler for Python 2.7 from https://www.microsoft.com/en-us/download/confirmation.aspx?id=44266.
3. pip install scapy==2.4.3rc1

Install python 2.7.2 and then install Microsoft Visual C++ Compiler for Python 2.7
