### ISSUE TITLE
ModuleNotFoundError: No module named 'Utils'

### ISSUE THREAD

**Issue by kirkcc** [andreafabrizi/rtmpSnoop#25]
Why this happen ??

D:\rtmpSnoop-master>python rtmpSnoop.py
Traceback (most recent call last):
  File "rtmpSnoop.py", line 28, in <module>
    from lib.rtmpParser import rtmpParser
  File "D:\rtmpSnoop-master\lib\rtmpParser.py", line 24, in <module>
    import Utils
ModuleNotFoundError: No module named 'Utils'

D:\rtmpSnoop-master>python rtmpSnoop.py -h
Traceback (most recent call last):
  File "rtmpSnoop.py", line 28, in <module>
    from lib.rtmpParser import rtmpParser
  File "D:\rtmpSnoop-master\lib\rtmpParser.py", line 24, in <module>
    import Utils
ModuleNotFoundError: No module named 'Utils'

D:\rtmpSnoop-master>

**Comment by chijiao** [comment]
same error

**Comment by Amoswuuuu** [comment]
I also encountered the same error, you can solve it as follows.

Use `from lib.Utils import *` instead of `import Utils` in your project.

This error is caused by different python versions，this project was written by Python2 and everyone is using Python3.

**Comment by crackevil** [comment]
py3 isolate source file path from sys.path, add it before you "absolute import" local module
